# Travis CI build file for Kitura-Cache.
# Kitura runs on OS X and Linux (Ubuntu).
# See the following URLs for further details on Travis CI
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/docker/
# https://docs.travis-ci.com/user/multi-os/

# whitelist (branches that should be built)
branches:
  only:
    - master
    - /^issue.*$/

notifications:
  slack:
    secure: "QMQ7BqKaPjtPUlFHqDsjJoYOWBBAPWrr2z6g8/SFI4kTpkyKDzJwB3cuimxyZvcXb6Yo2DM3+NOnYOEayJAtyBJhLOOK6gH6oBLsm+lHmEJiepVQ5BvYR2lRNAeR0iAbKcy078G6ozxAG+71C98kj+hfk2xB/uJSoXeIWpQZN8SgqUUd9FTX5gaEMVKDr32aC/wEkrG+7THqYxUGmLOE5DYVps34JSkThuS0exxF0s/T3vndXceXYW/srVO3sXfwragVyOj8x7sYOGNtSF9ZwKiGB1EI8S85TYFagse8Attk5aYIfo11HiSL5m3tD4Dthe888jPiz9Fyt3H5QBTsf6hQq5QV3fBC9p0RIM7Ga4pttms70Byo+UOVwq1rNm4MA8p7vq453cIJbAChWQ6/VJE5HRHPzeZaZwQk/dnLFNaqG0Q3DHUwDhK3GCL0vHj63jiaHzhIrVGR/CQsDsnIiO5r13XWnqA/GITjGZC5oH/T53tFdkju1nMDHPM012zz1MtuAg69ZjpmEzxHbpySj3+c6r135pXGuQT9JO7Bkkz1gPrURzccjzc6NlFvFOhjMBw6mI/nLCXgKKTbN9isXDRbsusOREvsW3Iz99qPjZYtr+kPgxgiie1f9B5BLiR7qqMosqesvk84B1qz1wQALinkCrIBZTgKU+wWZMccRcU="

matrix:
  include:
    - os: linux
      services: docker
      sudo: required
    - os: osx
      osx_image: xcode8
      sudo: required

before_install:
  - git submodule update --init --remote --merge --recursive

script:
  - ./Package-Builder/script_travis.sh $TRAVIS_OS_NAME $TRAVIS_BRANCH $TRAVIS_BUILD_DIR Kitura-Cache
